name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # ¡Este es el campo requerido!

      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4  # ✅ Versión actual (recomendada)
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk